from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import TextInput, Select, PasswordInput, ValidationError
from .models import CustomUser

class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = TextInput(attrs={'class': 'form-input'})
        self.fields['password'].widget = PasswordInput(attrs={'class': 'form-input'})

class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        # Style the autogenerated password fields
        for field in ['password1', 'password2']:
            if field in self.fields:
                self.fields[field].widget.attrs.update({'class': 'form-input'})

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and CustomUser.objects.filter(email=email).exists():
            raise ValidationError("A user with that email already exists.")
        return email

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email', 'role', 'phone_number', 'department')
        widgets = {
            'username': TextInput(attrs={'class': 'form-input'}),
            'email': TextInput(attrs={'class': 'form-input', 'type': 'email'}),
            'role': Select(attrs={'class': 'form-input'}),
            'phone_number': TextInput(attrs={'class': 'form-input'}),
            'department': TextInput(attrs={'class': 'form-input'}),
        }
